// elastic adaptive
export const SET_CURRENT_FONT_SIZE = 'SET_CURRENT_FONT_SIZE'
export const SET_USER_DEVICE_TYPE = 'SET_USER_DEVICE_TYPE'

// ui
export const SET_LANG = 'SET_LANG'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'

// data
export const SET_LOADING_STATE = 'SET_LOADING_STATE'
export const CONNECT_WALLET = 'CONNECT_WALLET'
export const GET_WALLET_BALANCE = 'GET_WALLET_BALANCE'
export const GET_AVAILABLE_TOKENS = 'GET_AVAILABLE_TOKENS'
export const GET_EXCHANGE_ESTIMATE = 'GET_EXCHANGE_ESTIMATE'
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
